version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
      time: "00:00"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"

  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "daily"
      time: "00:00"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
