ENABLED=false
API_URL=http://crowdsec:8080
API_KEY=
CACHE_EXPIRATION=1s
RETURN_CODE=403
MODE=stream
EXCLUDE_LOCATION=
FALLBACK_REMEDIATION=ban
MSG_CAPTCHA=Please complete the captcha.
MSG_BAN=Access forbidden.
