ENABLED=false
API_URL=http://crowdsec:8080
API_KEY=
CACHE_EXPIRATION=1s
BAN_TEMPLATE_PATH=/data/crowdsec/ban.html
CAPTCHA_TEMPLATE_PATH=/data/crowdsec/captcha.html
REDIRECT_LOCATION=
RET_CODE=
SECRET_KEY=
SITE_KEY=
REQUEST_TIMEOUT=5000
