import type { ProxyHost } from "src/api/backend";
import { FORWARD_SCHEME, ICON_TYPE, PHP_VERSION, TERMINAL_AUTH_TYPE, TIME_UNIT } from "src/types/enums";
import { describe, expect, it } from "vitest";
import { createProxyHostInitialValues } from "./ProxyHostModalFormValues";

describe("createProxyHostInitialValues", () => {
	it("initializes every ProxyHost form field with the existing safe defaults", () => {
		expect(createProxyHostInitialValues({})).toStrictEqual({
			accessListId: 0,
			advancedConfig: "",
			advLimitReqBurst: undefined,
			advLimitReqRate: undefined,
			advLimitReqUnit: TIME_UNIT.SECONDS,
			allowWebsocketUpgrade: false,
			anubisEnabled: false,
			anubisRules: [],
			bandwidthLimit: "",
			blockExploits: false,
			cachingEnabled: false,
			certificateId: 0,
			crowdsecEnabled: false,
			disableBuffering: false,
			domainNames: [],
			forwardHost: "",
			forwardPort: undefined,
			forwardQuery: "",
			forwardScheme: FORWARD_SCHEME.HTTP,
			gitBranch: "main",
			gitCredentials: "",
			gitPollInterval: 60,
			gitPollUnit: TIME_UNIT.MINUTES,
			gitRepoUrl: "",
			gitSyncEnabled: false,
			hstsEnabled: false,
			hstsSubdomains: false,
			http2Support: false,
			iconType: ICON_TYPE.AUTO,
			iconUrl: "",
			indexFile: "",
			locations: [],
			maintenanceActive: false,
			maintenanceEnd: "",
			maintenanceOnFailure: false,
			maintenanceReason: "",
			maintenanceStart: "",
			note: "",
			phpEnabled: false,
			phpVersion: PHP_VERSION.PHP83,
			sslForced: false,
			terminalAuthType: TERMINAL_AUTH_TYPE.PASSWORD,
			terminalHost: "",
			terminalPassword: "",
			terminalPort: 22,
			terminalPrivateKey: "",
			terminalUsername: "",
			turboLoader: false,
		});
	});

	it("preserves configured values while formatting maintenance timestamps for datetime-local fields", () => {
		const host = {
			accessListId: 4,
			advancedConfig: "proxy_read_timeout 60s;",
			advLimitReqBurst: 15,
			advLimitReqRate: 10,
			advLimitReqUnit: TIME_UNIT.MINUTES,
			allowWebsocketUpgrade: true,
			anubisEnabled: true,
			anubisRules: [{ action: "DENY", name: "block-bot", path: ".*", userAgent: "BadBot" }],
			bandwidthLimit: "10m",
			blockExploits: true,
			cachingEnabled: true,
			certificateId: 9,
			disableBuffering: true,
			domainNames: ["example.test"],
			forwardHost: "app",
			forwardPort: 8080,
			forwardQuery: "source=proxy",
			forwardScheme: FORWARD_SCHEME.PATH,
			gitBranch: "release",
			gitPollInterval: 5,
			gitPollUnit: TIME_UNIT.HOURS,
			gitRepoUrl: "https://git.example.test/team/app.git",
			gitSyncEnabled: true,
			hstsEnabled: true,
			hstsSubdomains: true,
			http2Support: true,
			iconType: ICON_TYPE.CUSTOM,
			iconUrl: "https://example.test/icon.svg",
			indexFile: "index.php",
			locations: [
				{
					advancedConfig: "",
					forwardHost: "api",
					forwardPort: 3000,
					forwardScheme: FORWARD_SCHEME.HTTP,
					path: "/api",
				},
			],
			maintenanceActive: true,
			maintenanceEnd: "2026-07-12T10:30:00.000Z",
			maintenanceOnFailure: true,
			maintenanceReason: "Deploy",
			maintenanceStart: "2026-07-12T09:30:00Z",
			note: "Production host",
			phpEnabled: true,
			phpVersion: PHP_VERSION.PHP84,
			securityCrowdsec: true,
			sslForced: true,
			terminalAuthType: TERMINAL_AUTH_TYPE.KEY,
			terminalHost: "terminal.example.test",
			terminalPassword: "",
			terminalPort: 2222,
			terminalPrivateKey: "private-key",
			terminalUsername: "deploy",
			turboLoader: true,
		} satisfies Partial<ProxyHost>;

		expect(createProxyHostInitialValues(host)).toMatchObject({
			accessListId: 4,
			advancedConfig: "proxy_read_timeout 60s;",
			advLimitReqBurst: 15,
			advLimitReqRate: 10,
			advLimitReqUnit: TIME_UNIT.MINUTES,
			allowWebsocketUpgrade: true,
			anubisEnabled: true,
			anubisRules: [{ action: "DENY", name: "block-bot", path: ".*", userAgent: "BadBot" }],
			bandwidthLimit: "10m",
			blockExploits: true,
			cachingEnabled: true,
			certificateId: 9,
			crowdsecEnabled: true,
			disableBuffering: true,
			domainNames: ["example.test"],
			forwardHost: "app",
			forwardPort: 8080,
			forwardQuery: "source=proxy",
			forwardScheme: FORWARD_SCHEME.PATH,
			gitBranch: "release",
			gitCredentials: "",
			gitPollInterval: 5,
			gitPollUnit: TIME_UNIT.HOURS,
			gitRepoUrl: "https://git.example.test/team/app.git",
			gitSyncEnabled: true,
			hstsEnabled: true,
			hstsSubdomains: true,
			http2Support: true,
			iconType: ICON_TYPE.CUSTOM,
			iconUrl: "https://example.test/icon.svg",
			indexFile: "index.php",
			locations: [
				{
					advancedConfig: "",
					forwardHost: "api",
					forwardPort: 3000,
					forwardScheme: FORWARD_SCHEME.HTTP,
					path: "/api",
				},
			],
			maintenanceActive: true,
			maintenanceEnd: "2026-07-12T10:30:00",
			maintenanceOnFailure: true,
			maintenanceReason: "Deploy",
			maintenanceStart: "2026-07-12T09:30:00",
			note: "Production host",
			phpEnabled: true,
			phpVersion: PHP_VERSION.PHP84,
			sslForced: true,
			terminalAuthType: TERMINAL_AUTH_TYPE.KEY,
			terminalHost: "terminal.example.test",
			terminalPassword: "",
			terminalPort: 2222,
			terminalPrivateKey: "private-key",
			terminalUsername: "deploy",
			turboLoader: true,
		});
	});
});
