import { download } from "./downloads.js";
import {
	allowedSslFiles,
	checkPrivateKey,
	cleanExpansions,
	cleanMeta,
	getCertificateInfo,
	getCertificateInfoFromFile,
	omissions,
	validate,
	zipFiles,
} from "./helpers.js";
import {
	addCreatedAuditLog,
	create,
	createQuickCertificate,
	getLiveCertPath,
	remove,
	requestCertbot,
	requestCertbotWithDnsChallenge,
	revokeCertbot,
	update,
	upload,
	writeCustomCert,
} from "./mutations.js";
import { get, getAll, getCount } from "./reads.js";
import {
	initTimer,
	interval,
	intervalProcessing,
	performTestForDomain,
	processExpiringHosts,
	processing,
	renew,
	renewCertbot,
	renewCertbotWithDnsChallenge,
	testHttpsChallenge,
} from "./renewal.js";

export default {
	allowedSslFiles,
	intervalTimeout: 1000 * 60 * 60 * Number.parseInt(process.env.CRT, 10),
	interval,
	intervalProcessing,
	processing,
	initTimer,
	processExpiringHosts,
	create,
	addCreatedAuditLog,
	update,
	get,
	cleanExpansions,
	download,
	zipFiles,
	delete: remove,
	getAll,
	getCount,
	writeCustomCert,
	createQuickCertificate,
	validate,
	upload,
	checkPrivateKey,
	getCertificateInfo,
	getCertificateInfoFromFile,
	cleanMeta,
	requestCertbot,
	requestCertbotWithDnsChallenge,
	renew,
	renewCertbot,
	renewCertbotWithDnsChallenge,
	revokeCertbot,
	testHttpsChallenge,
	performTestForDomain,
	getLiveCertPath,
	omissions,
};
