name: Dockerlint
on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  docker-lint:
    runs-on: ubuntu-latest
    name: docker-lint
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - name: Install hadolint
        run: |
          curl --proto '=https' --tlsv1.2 --fail --location \
            https://github.com/hadolint/hadolint/releases/download/v2.15.1/hadolint-linux-x86_64 \
            --output /tmp/hadolint
          echo 'c7187db94eeeeca956519a6af171adc31453941a1e777961f6e680f697c8c507  /tmp/hadolint' | sha256sum --check
          sudo install -m 0755 /tmp/hadolint /usr/local/bin/hadolint
      - name: Run lint
        shell: bash
        run: |
          while IFS= read -r -d '' file; do
            # DL3003 warning: Use WORKDIR to switch to a directory
            # DL3007 warning: Using latest is prone to errors if the image will ever update. Pin the version explicitly to a release tag
            # DL3008 warning: Pin versions in apt get install. Instead of `apt-get install <package>` use `apt-get install <package>=<version>`
            # DL3013 warning: Pin versions in pip. Instead of `pip install <package>` use `pip install <package>==<version>` or `pip install --requirement <requirements file>`
            hadolint "$file" --ignore DL3003 --ignore DL3007 --ignore DL3013 --ignore DL3008
          done < <(find . -type f -name '*Dockerfile*' -print0)
