name: JSON check
on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - name: json-syntax-check
        uses: limitusus/json-syntax-check@6e25e4304c75d72195ad8c6fca739cb2e99c3fb1 # v2.0.3
        with:
          pattern: "^(?!.*/\\.agent/).*\\.json$"
