name: Shellcheck
on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  shellcheck:
    name: Check Shell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Install Shellcheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck
      - name: Run Shellcheck
        run: |
          find . -type f -not -path "*/.agent/*" \( -name "*.sh" -o -name "*.bash" \) -exec shellcheck {} +
