name: spellcheck
on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  spellcheck:
    name: spellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Check out code.
        uses: actions/checkout@v6
      - name: Check spelling
        uses: codespell-project/actions-codespell@v2
        with:
          check_filenames: true
          check_hidden: true
          skip: yarn.lock,package-lock.json,./frontend/src/locale/lang,./frontend/src/locale/src
          ignore_words_list: afterAll,alog,nd,devlop,trough
