name: Wiki Sync

on:
  push:
    branches:
      - develop
    paths:
      - "docs/wiki/**"

jobs:
  sync-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Sync Wiki
        uses: JoeIzzard/ghaction-wiki-sync@v1.0.1
        with:
          wiki_folder: "docs/wiki"
          username: ${{ github.actor }}
          access_token: ${{ secrets.GITHUB_TOKEN }}
